#this pipeline will be trigger to run by master branch of github repo. 
trigger:
 - master

#add variables
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Job
    pool: MyLaptop01
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.Repository.LocalPath)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'

